version: '3.5'

services:
  backend_gateway:
    build: .
    container_name: backend_gateway
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    networks:
      - vant-network
    volumes:
      - ./:/code

networks:
  vant-network:
    name: vant-network
    driver: bridge